global:
  resolve_timeout: 1m

receivers:
  - name: "gmail-notifications"
    email_configs:
      - to: "thierno@gmail.com"
        from: "thierno@gmail.com"
        smarthost: smtp.gmail.com:587
        auth_username: "thierno@gmail.com"
        auth_identity: "thierno@gmail.com"
        auth_password: "ogrdzyvsuawrxxjk"
        send_resolved: true
        headers:
          subject: " Prometheus -  Alert "
        text: "{{ range .Alerts }} Hi, \n{{ .Annotations.summary }}  \n {{ .Annotations.description }} {{end}} "

route:
  group_wait: 10s
  group_interval: 2m
  receiver: "gmail-notifications"
  repeat_interval: 2m
  group_by: [alertname]
