global:
  scrape_interval: 5s
  external_labels:
    monitor: "Monitoring"
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["192.168.x.x:9090"]
  - job_name: "node-exporter"
    static_configs:
      - targets: ["192.168.x.x:9100"]
  - job_name: "cadvisor"
    static_configs:
      - targets: ["192.168.x.x:8081"]
  - job_name: "jenkins"
    metrics_path: /prometheus
    static_configs:
      - targets: ["192.168.x.x:8080"]
