global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
- "rules.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 192.168.xxx.xxx:9093

scrape_configs:
- job_name: "prometheus"
  static_configs:
  - targets: ["localhost:9090"]

- job_name: "node_exporter"
  static_configs:
  - targets: ["192.168.xxx.xxx:9100"]

- job_name: "jenkins"
  metrics_path: "/prometheus"
  static_configs:
  - targets: ["192.168.xxx.xxx:8080"]

- job_name: "cadvisor"
  static_configs:
  - targets: ["192.168.xxx.xxx:8081"]
