global:
  scrape_interval: 1m
  evaluation_interval: 15s

rule_files:
  - "rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 192.168.129.2:9093

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["192.168.129.2:9090"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["192.168.129.2:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["192.168.129.2:8081"]
